/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/usuarios/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Ver un usuario
     * @description Permiso: usuarios.ver.
     */
    get: operations['obtener'];
    /**
     * Editar usuario, correo y nombre
     * @description Permiso: usuarios.editar.
     */
    put: operations['editar'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/usuarios/{id}/roles': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Cambiar sus roles
     * @description Permiso: usuarios.asignar_roles. Sustituye todos sus roles.
     */
    put: operations['cambiarRoles'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/usuarios/{id}/password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Restablecer su contraseña
     * @description Permiso: usuarios.editar. Cierra todas sus sesiones. La propia contraseña se cambia en /api/auth/password.
     */
    put: operations['restablecerPassword'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/usuarios/{id}/estado': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Activar o desactivar
     * @description Permiso: usuarios.editar. Desactivar cierra sus sesiones al momento; activar quita también un bloqueo por intentos fallidos.
     */
    put: operations['cambiarEstado'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/roles/{id}/permisos': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Cambiar los permisos de un rol
     * @description Permiso: roles.editar. Sustituye todos sus permisos. Los del administrador no se pueden cambiar (409).
     */
    put: operations['cambiarPermisos'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/pacientes/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Ver un paciente
     * @description Permiso: pacientes.ver.
     */
    get: operations['obtener_1'];
    /**
     * Editar sus datos
     * @description Permiso: pacientes.editar. Sustituye todos sus datos.
     */
    put: operations['editar_1'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/pacientes/{id}/estado': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Dar de baja o reactivar
     * @description Permiso: pacientes.editar. Dar de baja no borra nada.
     */
    put: operations['cambiarEstado_1'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/configuracion/tratamientos/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Cambiar duración, precio, quién lo hace…
     * @description Permiso: tratamientos.gestionar. Las citas ya dadas no cambian; las nuevas usan la duración nueva.
     */
    put: operations['editar_2'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/configuracion/tratamientos/{id}/estado': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Ofrecerlo o dejar de ofrecerlo
     * @description Permiso: tratamientos.gestionar. No se borra nada. 409 si aún tiene citas pendientes o confirmadas.
     */
    put: operations['cambiarEstado_2'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/configuracion/odontologos/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Cambiar sus datos y su usuario del software
     * @description Permiso: odontologos.gestionar. 409 si el usuario ya está vinculado a otro odontólogo.
     */
    put: operations['editar_3'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/configuracion/odontologos/{id}/estado': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Activar o desactivar
     * @description Permiso: odontologos.gestionar. No se borra nada. 409 si aún tiene citas pendientes o confirmadas.
     */
    put: operations['cambiarEstado_3'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/configuracion/horarios/odontologos/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Cambiar los turnos de un odontólogo
     * @description Permiso: horarios.gestionar. Sustituye toda su semana. Devuelve las citas que quedan fuera de sus turnos nuevos (no se cancelan).
     */
    put: operations['cambiarTurnos'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/configuracion/horarios/clinica': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Cambiar el horario de la clínica
     * @description Permiso: horarios.gestionar. Sustituye toda la semana: el día que no se envía queda cerrado. Devuelve las citas que quedan fuera del horario nuevo (no se cancelan).
     */
    put: operations['cambiarClinica'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/configuracion/bloqueos/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Cambiar un bloqueo
     * @description Permiso: bloqueos.gestionar.
     */
    put: operations['editar_4'];
    post?: never;
    /**
     * Quitar un bloqueo
     * @description Permiso: bloqueos.gestionar. No se borra: queda desactivado y en la auditoría, y ese tiempo vuelve a estar libre al momento.
     */
    delete: operations['quitar'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/citas/{id}/paciente': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Vincular a la ficha de un paciente
     * @description Permiso: citas.editar.
     */
    put: operations['vincularPaciente'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/citas/{id}/notas': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Cambiar las notas internas
     * @description Permiso: citas.editar.
     */
    put: operations['cambiarNotas'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/citas/{id}/estado': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Cambiar el estado
     * @description Permiso: citas.cambiar_estado. Confirmar, en consulta, completada o no asistió; los estados posibles en cada momento vienen en estados_siguientes.
     */
    put: operations['cambiarEstado_4'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Cambiar mi contraseña
     * @description Pide la contraseña actual. Cierra las sesiones abiertas en otros equipos.
     */
    put: operations['cambiarPassword'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/usuarios': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Buscar usuarios
     * @description Permiso: usuarios.ver. Ordenados por nombre.
     */
    get: operations['buscar'];
    put?: never;
    /**
     * Crear un usuario
     * @description Permiso: usuarios.crear. Darle roles exige además usuarios.asignar_roles; el rol de administrador solo lo da un administrador.
     */
    post: operations['crear'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/pacientes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Buscar pacientes
     * @description Permiso: pacientes.ver. Ordenados por apellidos y nombre.
     */
    get: operations['buscar_1'];
    put?: never;
    /**
     * Dar de alta un paciente
     * @description Permiso: pacientes.crear. El código del paciente lo genera el backend.
     */
    post: operations['crear_1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/pacientes/{id}/citas': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Dar cita al paciente
     * @description Permiso: citas.crear. El horario se elige entre los de /api/agenda/disponibilidad y el backend comprueba otra vez que sigue libre (409 si alguien se adelantó). Queda CONFIRMADA. Es la misma tabla de citas que usa la landing: el hueco deja de ofrecerse en la web al momento.
     */
    post: operations['darCita'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/contacto': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['enviar'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/configuracion/tratamientos': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Todos los tratamientos
     * @description Permiso: tratamientos.gestionar. También los desactivados.
     */
    get: operations['listar'];
    put?: never;
    /**
     * Dar de alta un tratamiento
     * @description Permiso: tratamientos.gestionar. La duración va de 15 en 15 minutos.
     */
    post: operations['crear_2'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/configuracion/odontologos': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Todos los odontólogos
     * @description Permiso: odontologos.gestionar. También los desactivados.
     */
    get: operations['listar_1'];
    put?: never;
    /**
     * Dar de alta un odontólogo
     * @description Permiso: odontologos.gestionar. Sale en la web al momento; para tener huecos libres necesita turnos.
     */
    post: operations['crear_3'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/configuracion/bloqueos': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Bloqueos en vigor
     * @description Permiso: bloqueos.gestionar. Los que no han terminado.
     */
    get: operations['listar_2'];
    put?: never;
    /**
     * Bloquear tiempo
     * @description Permiso: bloqueos.gestionar. Se aplica al momento en la web y en el software. Devuelve las citas que ya había en ese tiempo (no se cancelan).
     */
    post: operations['crear_4'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/citas': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Buscar citas
     * @description Permiso: citas.ver. Sin citas.ver_todas, solo las del odontólogo vinculado al usuario.
     */
    get: operations['buscar_2'];
    put?: never;
    /**
     * Reservar una cita desde la web
     * @description Público. Entra PENDIENTE hasta que la clínica la confirma.
     */
    post: operations['reservar'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/citas/{id}/reprogramacion': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reprogramar
     * @description Permiso: citas.reprogramar. Devuelve la cita nueva; la anterior queda REPROGRAMADA. 409 si el nuevo horario ya no está libre (entonces no cambia nada).
     */
    post: operations['reprogramar'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/citas/{id}/cancelacion': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Cancelar
     * @description Permiso: citas.cancelar. No se borra: queda CANCELADA y su hueco libre.
     */
    post: operations['cancelar'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/citas/cancelacion': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Cancelar una cita desde la web
     * @description Público. El paciente se identifica con el código que recibió al reservar y debe hacerlo con la antelación mínima (409 si no). El hueco queda libre al momento.
     */
    post: operations['cancelarComoPaciente'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Renovar el token de acceso
     * @description Usa la cookie de sesión. 401 si la sesión caducó o se cerró.
     */
    post: operations['renovar'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Cerrar sesión
     * @description Cierra la sesión de la cookie y la borra.
     */
    post: operations['cerrar'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Iniciar sesión
     * @description Con usuario o correo y contraseña. Devuelve el token de acceso y deja el de refresco en una cookie HttpOnly. 401 si los datos no son correctos; 423 si la cuenta está bloqueada por intentos fallidos.
     */
    post: operations['login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/tratamientos': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['listar_3'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/tratamientos/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['obtener_2'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/roles': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Roles con sus permisos
     * @description Permiso: roles.ver o usuarios.asignar_roles (para elegir los roles de un usuario).
     */
    get: operations['listar_4'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/permisos': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Todos los permisos que existen
     * @description Permiso: roles.ver.
     */
    get: operations['permisos'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/odontologos': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['listar_5'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/odontologos/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['obtener_3'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['health'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/disponibilidad': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['dia'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/disponibilidad/proximos': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['proximos'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/configuracion/odontologos/usuarios': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Usuarios que se pueden vincular
     * @description Permiso: odontologos.gestionar. Usuarios activos, con el odontólogo al que ya está unido cada uno.
     */
    get: operations['usuarios'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/configuracion/horarios': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Horario de la clínica y turnos de cada odontólogo activo
     * @description Permiso: horarios.gestionar.
     */
    get: operations['obtener_4'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/citas/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Ver una cita
     * @description Permiso: citas.ver. 404 si no existe o es de otra agenda.
     */
    get: operations['obtener_5'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Usuario con sesión iniciada
     * @description Sus datos, roles y permisos.
     */
    get: operations['yo'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auditoria': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Consultar la auditoría
     * @description Permiso: auditoria.ver. De lo más reciente a lo más antiguo.
     */
    get: operations['buscar_3'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/agenda': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Agenda de uno o varios días
     * @description Permiso: citas.ver. Sin citas.ver_todas, solo la del odontólogo vinculado al usuario.
     */
    get: operations['agenda'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/agenda/disponibilidad': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Huecos libres de un día
     * @description Permiso: citas.crear o citas.reprogramar. Cada odontólogo por separado y sin la antelación mínima de la web. Al reprogramar, excluir_cita_id hace que la propia cita no cuente como ocupada.
     */
    get: operations['disponibilidad'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    UsuarioEdicionRequest: {
      username: string;
      /** Format: email */
      email: string;
      nombre: string;
    };
    RolResumen: {
      codigo: string;
      nombre: string;
    };
    /** @description Usuario del software de gestión. Las fechas están en hora de Madrid. */
    UsuarioResponse: {
      /** Format: int64 */
      id: number;
      username: string;
      email: string;
      nombre: string;
      activo: boolean;
      /** @description Bloqueado temporalmente por demasiados intentos fallidos */
      bloqueado: boolean;
      /** Format: date-time */
      bloqueado_hasta?: string;
      /** Format: date-time */
      ultimo_acceso?: string;
      /** Format: date-time */
      creado_en: string;
      roles: components['schemas']['RolResumen'][];
    };
    RolesUsuarioRequest: {
      roles: string[];
    };
    PasswordRequest: {
      password: string;
    };
    EstadoUsuarioRequest: {
      activo: boolean;
    };
    PermisosRolRequest: {
      permisos: string[];
    };
    /** @description Rol con sus permisos */
    RolResponse: {
      /** Format: int64 */
      id: number;
      codigo: string;
      nombre: string;
      descripcion?: string;
      /** @description false en el administrador: tiene siempre todos los permisos */
      editable: boolean;
      /**
       * Format: int64
       * @description Usuarios que tienen este rol
       */
      usuarios: number;
      /** @description Códigos de sus permisos */
      permisos: string[];
    };
    PacienteRequest: {
      nombres: string;
      apellidos: string;
      /**
       * @description Obligatorio si se indica el número de documento
       * @enum {string}
       */
      tipo_documento?: 'DNI' | 'NIE' | 'PASAPORTE' | 'OTRO';
      /** @description DNI y NIE se comprueban con su letra de control */
      numero_documento?: string;
      /** Format: date */
      fecha_nacimiento?: string;
      /** @enum {string} */
      sexo?: 'MUJER' | 'HOMBRE' | 'OTRO';
      telefono: string;
      /** Format: email */
      email?: string;
      direccion?: string;
      /** @description Nombre y, si se quiere, la relación entre paréntesis: Ana Pérez (madre) */
      contacto_emergencia_nombre?: string;
      contacto_emergencia_telefono?: string;
      /** @description Solo datos administrativos; la información clínica va en el expediente */
      observaciones?: string;
    };
    /** @description Paciente con sus datos personales, de contacto y administrativos. Las fechas están en hora de Madrid. */
    PacienteResponse: {
      /** Format: int64 */
      id: number;
      /** @description Código del paciente para la clínica, por ejemplo K7M3QX */
      codigo: string;
      nombres: string;
      apellidos: string;
      /** @enum {string} */
      tipo_documento?: 'DNI' | 'NIE' | 'PASAPORTE' | 'OTRO';
      numero_documento?: string;
      /** Format: date */
      fecha_nacimiento?: string;
      /**
       * Format: int32
       * @description Años cumplidos hoy
       */
      edad?: number;
      /** @enum {string} */
      sexo?: 'MUJER' | 'HOMBRE' | 'OTRO';
      /** @description Solo dígitos, con + delante si lleva prefijo internacional */
      telefono: string;
      email?: string;
      direccion?: string;
      contacto_emergencia_nombre?: string;
      contacto_emergencia_telefono?: string;
      observaciones?: string;
      /** @description false = dado de baja */
      activo: boolean;
      /** Format: date-time */
      creado_en: string;
      /** Format: date-time */
      actualizado_en: string;
    };
    EstadoPacienteRequest: {
      activo: boolean;
    };
    TratamientoConfigRequest: {
      nombre: string;
      descripcion_corta?: string;
      /** @description Precio orientativo «desde», en euros. 0 o vacío = la web lo muestra como gratuito */
      precio_desde?: number;
      /**
       * @description Duración orientativa en texto, por ejemplo «2 o 3 sesiones». Las citas usan duracion_minutos
       * @example 30–45 min
       */
      duracion_aproximada?: string;
      /**
       * Format: int32
       * @example 60
       */
      duracion_minutos: number;
      /** @description Quién lo hace; vacío = cualquier odontólogo */
      odontologo_ids?: number[];
    };
    OdontologoAsignado: {
      /** Format: int64 */
      id: number;
      nombre: string;
      activo: boolean;
    };
    TratamientoConfigResponse: {
      /** Format: int64 */
      id: number;
      nombre: string;
      descripcion_corta?: string;
      precio_desde?: number;
      duracion_aproximada?: string;
      /** Format: int32 */
      duracion_minutos?: number;
      activo: boolean;
      odontologos: components['schemas']['OdontologoAsignado'][];
    };
    ActivacionRequest: {
      activo: boolean;
    };
    OdontologoConfigRequest: {
      /** @example Dra. Ana Villar */
      nombre: string;
      especialidad?: string;
      descripcion?: string;
      /**
       * Format: int64
       * @description Su usuario del software, para que vea su propia agenda; vacío = sin usuario
       */
      usuario_id?: number;
    };
    OdontologoConfigResponse: {
      /** Format: int64 */
      id: number;
      nombre: string;
      especialidad?: string;
      descripcion?: string;
      activo: boolean;
      usuario?: components['schemas']['UsuarioResumen'];
      tratamientos: string[];
    };
    UsuarioResumen: {
      /** Format: int64 */
      id: number;
      username: string;
      nombre: string;
    };
    /** @description Puede haber varios tramos el mismo día; un día sin tramos no trabaja */
    TurnoSemanal: {
      /**
       * Format: int32
       * @example 1
       */
      dia_semana: number;
      /** @example 09:00 */
      hora_inicio: string;
      /** @example 13:00 */
      hora_fin: string;
    };
    TurnosRequest: {
      /** @description Puede haber varios tramos el mismo día; un día sin tramos no trabaja */
      turnos: components['schemas']['TurnoSemanal'][];
    };
    /** @description Cita en la agenda o en un listado */
    CitaResumenResponse: {
      /** Format: int64 */
      id: number;
      /** Format: date */
      fecha: string;
      /** @example 10:30 */
      hora_inicio: string;
      /** @example 11:30 */
      hora_fin: string;
      /** @enum {string} */
      estado:
        | 'PENDIENTE'
        | 'CONFIRMADA'
        | 'EN_ATENCION'
        | 'COMPLETADA'
        | 'NO_ASISTIO'
        | 'CANCELADA'
        | 'REPROGRAMADA';
      /** @enum {string} */
      origen: 'LANDING' | 'SOFTWARE' | 'APP';
      /** Format: int64 */
      tratamiento_id: number;
      tratamiento: string;
      /** Format: int64 */
      odontologo_id: number;
      odontologo: string;
      /**
       * Format: int64
       * @description Ficha del paciente; vacío si la cita (de la web) aún no está vinculada
       */
      paciente_id?: number;
      /** @description Nombre del paciente: el de su ficha o, sin ficha, el que escribió en la web */
      nombre: string;
      /** @description Teléfono de su ficha o, sin ficha, el que dejó en la web */
      telefono: string;
    };
    CitasAfectadasResponse: {
      /** Format: int32 */
      total: number;
      citas?: components['schemas']['CitaResumenResponse'][];
    };
    DiaDeApertura: {
      /**
       * Format: int32
       * @example 1
       */
      dia_semana: number;
      /** @example 09:00 */
      hora_apertura: string;
      /** @example 21:00 */
      hora_cierre: string;
    };
    HorariosGuardadosResponse: {
      horarios: components['schemas']['HorariosResponse'];
      citas_afectadas: components['schemas']['CitasAfectadasResponse'];
    };
    HorariosResponse: {
      clinica: components['schemas']['DiaDeApertura'][];
      odontologos: components['schemas']['TurnosDeOdontologo'][];
    };
    TurnosDeOdontologo: {
      /** Format: int64 */
      id: number;
      nombre: string;
      turnos: components['schemas']['TurnoSemanal'][];
    };
    HorarioClinicaRequest: {
      /** @description Días en que abre; el que no aparece queda cerrado */
      dias: components['schemas']['DiaDeApertura'][];
    };
    BloqueoRequest: {
      /** @enum {string} */
      tipo: 'ALMUERZO' | 'REUNION' | 'CAPACITACION' | 'MANTENIMIENTO' | 'VACACIONES' | 'FERIADO' | 'MANUAL';
      motivo?: string;
      /**
       * Format: int64
       * @description Vacío = toda la clínica
       */
      odontologo_id?: number;
      /**
       * Format: date
       * @description Primer día. Vacío = desde siempre (solo con día de la semana)
       */
      fecha_inicio?: string;
      /**
       * Format: date
       * @description Último día, incluido. Vacío = solo el primer día; con día de la semana, sin fin
       */
      fecha_fin?: string;
      /**
       * Format: int32
       * @description Cada semana ese día: 1 = lunes … 7 = domingo
       */
      dia_semana?: number;
      /**
       * @description Vacías las dos horas = el día entero
       * @example 09:00
       */
      hora_inicio?: string;
      /** @example 10:00 */
      hora_fin?: string;
    };
    BloqueoGuardadoResponse: {
      bloqueo: components['schemas']['BloqueoResponse'];
      citas_afectadas: components['schemas']['CitasAfectadasResponse'];
    };
    BloqueoResponse: {
      /** Format: int64 */
      id: number;
      /** @enum {string} */
      tipo: 'ALMUERZO' | 'REUNION' | 'CAPACITACION' | 'MANTENIMIENTO' | 'VACACIONES' | 'FERIADO' | 'MANUAL';
      motivo?: string;
      /** Format: int64 */
      odontologo_id?: number;
      odontologo?: string;
      /** Format: date */
      fecha_inicio?: string;
      /** Format: date */
      fecha_fin?: string;
      /**
       * Format: int32
       * @description 1 = lunes … 7 = domingo
       */
      dia_semana?: number;
      /** @example 12:00 */
      hora_inicio?: string;
      /** @example 13:00 */
      hora_fin?: string;
    };
    PacienteCitaRequest: {
      /** Format: int64 */
      paciente_id: number;
    };
    /** @description Cita completa para el personal. Las fechas están en hora de Madrid. */
    CitaDetalleResponse: {
      /** Format: int64 */
      id: number;
      /** Format: date */
      fecha: string;
      /** @example 10:30 */
      hora_inicio: string;
      /** @example 11:30 */
      hora_fin: string;
      /** Format: int32 */
      duracion_minutos: number;
      /** @enum {string} */
      estado:
        | 'PENDIENTE'
        | 'CONFIRMADA'
        | 'EN_ATENCION'
        | 'COMPLETADA'
        | 'NO_ASISTIO'
        | 'CANCELADA'
        | 'REPROGRAMADA';
      /** @enum {string} */
      origen: 'LANDING' | 'SOFTWARE' | 'APP';
      /** Format: int64 */
      tratamiento_id: number;
      tratamiento: string;
      /** Format: int64 */
      odontologo_id: number;
      odontologo: string;
      paciente?: components['schemas']['PacienteDeCita'];
      contacto: components['schemas']['ContactoDeCita'];
      notas_internas?: string;
      /** @description Quién la dio desde el software; vacío si llegó por la web */
      creada_por?: string;
      /** Format: date-time */
      creada_en: string;
      /** Format: date-time */
      actualizada_en: string;
      /** Format: date-time */
      cancelada_en?: string;
      /** @enum {string} */
      cancelada_por?: 'LANDING' | 'SOFTWARE' | 'APP';
      motivo_cancelacion?: string;
      /**
       * Format: int64
       * @description Si es una reprogramación, la cita a la que sustituye
       */
      cita_anterior_id?: number;
      /**
       * Format: int64
       * @description Si se reprogramó, la cita nueva
       */
      cita_nueva_id?: number;
      /** @description Estados a los que se puede pasar ahora con PUT /api/citas/{id}/estado */
      estados_siguientes: (
        | 'PENDIENTE'
        | 'CONFIRMADA'
        | 'EN_ATENCION'
        | 'COMPLETADA'
        | 'NO_ASISTIO'
        | 'CANCELADA'
        | 'REPROGRAMADA'
      )[];
      /** @description true = todavía se puede cancelar o reprogramar */
      modificable: boolean;
    };
    /** @description Datos de contacto con los que llegó la cita */
    ContactoDeCita: {
      nombre: string;
      telefono: string;
      email?: string;
      /** @description Lo que escribió el paciente al reservar en la web */
      mensaje?: string;
    };
    /** @description Ficha del paciente; vacío si la cita (de la web) aún no está vinculada */
    PacienteDeCita: {
      /** Format: int64 */
      id: number;
      codigo: string;
      nombre: string;
      telefono: string;
      email?: string;
    };
    NotasCitaRequest: {
      notas_internas?: string;
    };
    EstadoCitaRequest: {
      /** @enum {string} */
      estado:
        | 'PENDIENTE'
        | 'CONFIRMADA'
        | 'EN_ATENCION'
        | 'COMPLETADA'
        | 'NO_ASISTIO'
        | 'CANCELADA'
        | 'REPROGRAMADA';
    };
    CambioPasswordRequest: {
      password_actual: string;
      password_nueva: string;
    };
    UsuarioCreacionRequest: {
      username: string;
      /** Format: email */
      email: string;
      nombre: string;
      password: string;
      roles?: string[];
    };
    NuevaCitaRequest: {
      /** Format: int64 */
      tratamiento_id: number;
      /** Format: int64 */
      odontologo_id: number;
      /** Format: date */
      fecha: string;
      /** @example 10:30 */
      hora_inicio: string;
      /** @description Notas para el personal; el paciente no las ve */
      notas_internas?: string;
    };
    ContactoRequest: {
      nombre: string;
      telefono: string;
      /** Format: email */
      email: string;
      tratamiento?: string;
      mensaje?: string;
    };
    ApiResponse: {
      success?: boolean;
      message?: string;
      errores?: {
        [key: string]: string;
      };
      datos?: Record<string, never>;
    };
    CitaRequest: {
      /** Format: int64 */
      tratamiento_id: number;
      /** Format: int64 */
      odontologo_id: number;
      /** Format: date */
      fecha: string;
      /** Format: time-local */
      hora_inicio: string;
      nombre: string;
      telefono: string;
      /** Format: email */
      email: string;
      mensaje?: string;
    };
    ReprogramacionRequest: {
      /** Format: int64 */
      odontologo_id: number;
      /** Format: date */
      fecha: string;
      /** @example 10:30 */
      hora_inicio: string;
    };
    CancelacionRequest: {
      motivo?: string;
    };
    CancelacionPacienteRequest: {
      /** @description El código que devolvió la reserva */
      codigo: string;
    };
    /** @description Sesión iniciada */
    SesionResponse: {
      /** @description Token de acceso (JWT) de corta duración */
      token_acceso: string;
      /** @example Bearer */
      tipo: string;
      /**
       * Format: int64
       * @description Segundos que dura el token de acceso
       * @example 900
       */
      expira_en: number;
      usuario: components['schemas']['UsuarioActualResponse'];
    };
    /** @description Usuario con sesión iniciada */
    UsuarioActualResponse: {
      /** Format: int64 */
      id: number;
      username: string;
      email: string;
      nombre: string;
      roles: components['schemas']['RolResumen'][];
      /**
       * @description Códigos de los permisos que suman sus roles
       * @example [
       *       "usuarios.ver",
       *       "auditoria.ver"
       *     ]
       */
      permisos: string[];
    };
    LoginRequest: {
      usuario: string;
      password: string;
    };
    /** @description Página de resultados */
    PaginaResponseUsuarioResponse: {
      contenido: components['schemas']['UsuarioResponse'][];
      /**
       * Format: int32
       * @description Número de página, empezando en 0
       */
      pagina: number;
      /**
       * Format: int32
       * @description Resultados por página
       */
      tamano: number;
      /** Format: int64 */
      total_elementos: number;
      /** Format: int32 */
      total_paginas: number;
    };
    TratamientoResponse: {
      /** Format: int64 */
      id: number;
      nombre: string;
      descripcion?: string;
      descripcion_corta?: string;
      precio_desde?: number;
      duracion_aproximada?: string;
      /** Format: int32 */
      duracion_minutos?: number;
      imagen?: string;
      odontologo_ids: number[];
    };
    PermisoResponse: {
      /** Format: int64 */
      id: number;
      codigo: string;
      modulo: string;
      descripcion: string;
    };
    /** @description Página de resultados */
    PaginaResponsePacienteResponse: {
      contenido: components['schemas']['PacienteResponse'][];
      /**
       * Format: int32
       * @description Número de página, empezando en 0
       */
      pagina: number;
      /**
       * Format: int32
       * @description Resultados por página
       */
      tamano: number;
      /** Format: int64 */
      total_elementos: number;
      /** Format: int32 */
      total_paginas: number;
    };
    OdontologoResponse: {
      /** Format: int64 */
      id: number;
      nombre: string;
      especialidad?: string;
      descripcion?: string;
      imagen?: string;
    };
    DisponibilidadResponse: {
      /** Format: date */
      fecha?: string;
      tratamiento?: components['schemas']['TratamientoResumen'];
      horarios?: components['schemas']['HorarioDisponibleResponse'][];
      proximas_opciones?: components['schemas']['HorarioDisponibleResponse'][];
      mensaje?: string;
    };
    HorarioDisponibleResponse: {
      /** Format: date */
      fecha?: string;
      /** Format: time-local */
      hora_inicio?: string;
      /** Format: time-local */
      hora_fin?: string;
      /** Format: int64 */
      odontologo_id?: number;
      odontologo_nombre?: string;
      odontologo_especialidad?: string;
    };
    TratamientoResumen: {
      /** Format: int64 */
      id?: number;
      nombre?: string;
      /** Format: int32 */
      duracion_minutos?: number;
    };
    UsuarioParaOdontologoResponse: {
      /** Format: int64 */
      id: number;
      username: string;
      nombre: string;
      roles: string[];
      /** Format: int64 */
      odontologo_id?: number;
      odontologo?: string;
    };
    /** @description Página de resultados */
    PaginaResponseCitaResumenResponse: {
      contenido: components['schemas']['CitaResumenResponse'][];
      /**
       * Format: int32
       * @description Número de página, empezando en 0
       */
      pagina: number;
      /**
       * Format: int32
       * @description Resultados por página
       */
      tamano: number;
      /** Format: int64 */
      total_elementos: number;
      /** Format: int32 */
      total_paginas: number;
    };
    /** @description Operación registrada en la auditoría. La fecha está en hora de Madrid. */
    AuditoriaResponse: {
      /** Format: int64 */
      id: number;
      /** Format: date-time */
      creado_en: string;
      usuario?: components['schemas']['UsuarioResumen'];
      /** @enum {string} */
      origen: 'LANDING' | 'SOFTWARE' | 'APP' | 'SISTEMA';
      /** @enum {string} */
      accion:
        | 'INICIAR_SESION'
        | 'INICIO_SESION_FALLIDO'
        | 'BLOQUEAR_POR_INTENTOS'
        | 'CERRAR_SESION'
        | 'CAMBIAR_PASSWORD'
        | 'RESTABLECER_PASSWORD'
        | 'CREAR'
        | 'EDITAR'
        | 'ACTIVAR'
        | 'DESACTIVAR'
        | 'CAMBIAR_ROLES'
        | 'CAMBIAR_PERMISOS'
        | 'RESERVAR'
        | 'CANCELAR'
        | 'REPROGRAMAR'
        | 'CAMBIAR_ESTADO'
        | 'VINCULAR_PACIENTE';
      /** @enum {string} */
      entidad:
        | 'USUARIO'
        | 'ROL'
        | 'CITA'
        | 'PACIENTE'
        | 'ODONTOLOGO'
        | 'TRATAMIENTO'
        | 'HORARIO_CLINICA'
        | 'HORARIO_ODONTOLOGO'
        | 'BLOQUEO';
      entidad_id?: string;
      valor_anterior?: components['schemas']['JsonNode'];
      valor_nuevo?: components['schemas']['JsonNode'];
      ip?: string;
    };
    /** @description Datos en formato JSON */
    JsonNode: {
      [key: string]: unknown;
    };
    /** @description Página de resultados */
    PaginaResponseAuditoriaResponse: {
      contenido: components['schemas']['AuditoriaResponse'][];
      /**
       * Format: int32
       * @description Número de página, empezando en 0
       */
      pagina: number;
      /**
       * Format: int32
       * @description Resultados por página
       */
      tamano: number;
      /** Format: int64 */
      total_elementos: number;
      /** Format: int32 */
      total_paginas: number;
    };
    AgendaResponse: {
      /** Format: date */
      desde: string;
      /** Format: date */
      hasta: string;
      dias: components['schemas']['Dia'][];
      /** @description Odontólogos que se muestran, en orden */
      odontologos: components['schemas']['OdontologoDeAgenda'][];
      turnos: components['schemas']['Turno'][];
      bloqueos: components['schemas']['BloqueoDelDia'][];
      /** @description Citas que ocupan su hueco (las canceladas y reprogramadas no salen) */
      citas: components['schemas']['CitaResumenResponse'][];
      /** @description true = el usuario solo puede ver la agenda del odontólogo vinculado a él */
      solo_su_agenda: boolean;
    };
    BloqueoDelDia: {
      /**
       * Format: int64
       * @description Vacío = toda la clínica
       */
      odontologo_id?: number;
      /** Format: date */
      fecha: string;
      /** @description Vacías = el día entero */
      hora_inicio?: string;
      hora_fin?: string;
      /** @enum {string} */
      tipo: 'ALMUERZO' | 'REUNION' | 'CAPACITACION' | 'MANTENIMIENTO' | 'VACACIONES' | 'FERIADO' | 'MANUAL';
      motivo?: string;
    };
    Dia: {
      /** Format: date */
      fecha: string;
      /** @description Vacío = la clínica cierra ese día */
      apertura?: string;
      cierre?: string;
    };
    /** @description Odontólogos que se muestran, en orden */
    OdontologoDeAgenda: {
      /** Format: int64 */
      id: number;
      nombre: string;
    };
    Turno: {
      /** Format: int64 */
      odontologo_id: number;
      /** Format: date */
      fecha: string;
      hora_inicio: string;
      hora_fin: string;
    };
    /** @description Hueco libre para dar o mover una cita */
    HuecoResponse: {
      /** Format: int64 */
      odontologo_id: number;
      odontologo: string;
      /** @example 10:30 */
      hora_inicio: string;
      /** @example 11:30 */
      hora_fin: string;
    };
    /** @description Error de la API */
    ErrorResponse: {
      /**
       * Format: date-time
       * @description Momento del error
       * @example 2026-10-12T10:25:00+02:00
       */
      timestamp: string;
      /**
       * Format: int32
       * @description Código HTTP
       * @example 409
       */
      status: number;
      /**
       * @description Nombre del código HTTP
       * @example CONFLICT
       */
      error: string;
      /**
       * @description Mensaje para mostrar a la persona
       * @example Este horario acaba de ser reservado. Selecciona otra opción.
       */
      message: string;
      /**
       * @description Ruta de la petición
       * @example /api/citas
       */
      path: string;
      /**
       * @description Un mensaje por cada campo con datos no válidos
       * @example {
       *       "email": "Escribe un correo válido."
       *     }
       */
      errores?: {
        [key: string]: string;
      };
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  obtener: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UsuarioResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  editar: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UsuarioEdicionRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UsuarioResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  cambiarRoles: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RolesUsuarioRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UsuarioResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  restablecerPassword: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  cambiarEstado: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EstadoUsuarioRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UsuarioResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  cambiarPermisos: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PermisosRolRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RolResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  obtener_1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PacienteResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  editar_1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PacienteRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PacienteResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  cambiarEstado_1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EstadoPacienteRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PacienteResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  editar_2: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TratamientoConfigRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TratamientoConfigResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  cambiarEstado_2: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ActivacionRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TratamientoConfigResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  editar_3: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['OdontologoConfigRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OdontologoConfigResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  cambiarEstado_3: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ActivacionRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OdontologoConfigResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  cambiarTurnos: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TurnosRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HorariosGuardadosResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  cambiarClinica: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['HorarioClinicaRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HorariosGuardadosResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  editar_4: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['BloqueoRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BloqueoGuardadoResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  quitar: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  vincularPaciente: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PacienteCitaRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CitaDetalleResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  cambiarNotas: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['NotasCitaRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CitaDetalleResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  cambiarEstado_4: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EstadoCitaRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CitaDetalleResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  cambiarPassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CambioPasswordRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  buscar: {
    parameters: {
      query?: {
        /** @description Parte del nombre, del usuario o del correo */
        texto?: string;
        /** @description true = activos, false = desactivados, vacío = todos */
        activo?: boolean;
        pagina?: number;
        tamano?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginaResponseUsuarioResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  crear: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UsuarioCreacionRequest'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UsuarioResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  buscar_1: {
    parameters: {
      query?: {
        /** @description Palabras del nombre, los apellidos, el documento, el teléfono, el correo o el código */
        texto?: string;
        /** @description true = activos, false = dados de baja, vacío = todos */
        activo?: boolean;
        pagina?: number;
        tamano?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginaResponsePacienteResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  crear_1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PacienteRequest'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PacienteResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  darCita: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['NuevaCitaRequest'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CitaDetalleResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  enviar: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ContactoRequest'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  listar: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TratamientoConfigResponse'][];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  crear_2: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TratamientoConfigRequest'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TratamientoConfigResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  listar_1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OdontologoConfigResponse'][];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  crear_3: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['OdontologoConfigRequest'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OdontologoConfigResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  listar_2: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BloqueoResponse'][];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  crear_4: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['BloqueoRequest'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BloqueoGuardadoResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  buscar_2: {
    parameters: {
      query?: {
        /** @description Desde este día (incluido) */
        desde?: string;
        /** @description Hasta este día (incluido) */
        hasta?: string;
        odontologo_id?: number;
        estado?:
          | 'PENDIENTE'
          | 'CONFIRMADA'
          | 'EN_ATENCION'
          | 'COMPLETADA'
          | 'NO_ASISTIO'
          | 'CANCELADA'
          | 'REPROGRAMADA';
        origen?: 'LANDING' | 'SOFTWARE' | 'APP';
        paciente_id?: number;
        /** @description true = solo las que aún no están vinculadas a la ficha de un paciente */
        sin_ficha?: boolean;
        /** @description true = de la más reciente a la más antigua */
        recientes?: boolean;
        pagina?: number;
        tamano?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginaResponseCitaResumenResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  reservar: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CitaRequest'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  reprogramar: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReprogramacionRequest'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CitaDetalleResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  cancelar: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CancelacionRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CitaDetalleResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  cancelarComoPaciente: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CancelacionPacienteRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  renovar: {
    parameters: {
      query?: never;
      header: {
        /**
         * @description Siempre XMLHttpRequest. Protege la cookie de sesión frente a peticiones desde otras webs.
         * @example XMLHttpRequest
         */
        'X-Requested-With': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SesionResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  cerrar: {
    parameters: {
      query?: never;
      header: {
        /**
         * @description Siempre XMLHttpRequest. Protege la cookie de sesión frente a peticiones desde otras webs.
         * @example XMLHttpRequest
         */
        'X-Requested-With': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SesionResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  listar_3: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TratamientoResponse'][];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  obtener_2: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TratamientoResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  listar_4: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RolResponse'][];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  permisos: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PermisoResponse'][];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  listar_5: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OdontologoResponse'][];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  obtener_3: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OdontologoResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  dia: {
    parameters: {
      query: {
        tratamiento_id: number;
        fecha: string;
        odontologo_id?: number;
        franja?: 'MANANA' | 'TARDE';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DisponibilidadResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  proximos: {
    parameters: {
      query: {
        tratamiento_id: number;
        desde?: string;
        odontologo_id?: number;
        franja?: 'MANANA' | 'TARDE';
        limite?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DisponibilidadResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  usuarios: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UsuarioParaOdontologoResponse'][];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  obtener_4: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HorariosResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  obtener_5: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CitaDetalleResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  yo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UsuarioActualResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  buscar_3: {
    parameters: {
      query?: {
        entidad?:
          | 'USUARIO'
          | 'ROL'
          | 'CITA'
          | 'PACIENTE'
          | 'ODONTOLOGO'
          | 'TRATAMIENTO'
          | 'HORARIO_CLINICA'
          | 'HORARIO_ODONTOLOGO'
          | 'BLOQUEO';
        /** @description Identificador del registro afectado */
        entidad_id?: string;
        /** @description Quién lo hizo */
        usuario_id?: number;
        accion?:
          | 'INICIAR_SESION'
          | 'INICIO_SESION_FALLIDO'
          | 'BLOQUEAR_POR_INTENTOS'
          | 'CERRAR_SESION'
          | 'CAMBIAR_PASSWORD'
          | 'RESTABLECER_PASSWORD'
          | 'CREAR'
          | 'EDITAR'
          | 'ACTIVAR'
          | 'DESACTIVAR'
          | 'CAMBIAR_ROLES'
          | 'CAMBIAR_PERMISOS'
          | 'RESERVAR'
          | 'CANCELAR'
          | 'REPROGRAMAR'
          | 'CAMBIAR_ESTADO'
          | 'VINCULAR_PACIENTE';
        /** @description Desde este día (incluido), hora de Madrid */
        desde?: string;
        /** @description Hasta este día (incluido), hora de Madrid */
        hasta?: string;
        pagina?: number;
        tamano?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginaResponseAuditoriaResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  agenda: {
    parameters: {
      query: {
        /** @description Primer día */
        desde: string;
        /** @description Cuántos días, de 1 a 7 */
        dias?: number;
        /** @description Solo este odontólogo */
        odontologo_id?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AgendaResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  disponibilidad: {
    parameters: {
      query: {
        tratamiento_id: number;
        fecha: string;
        odontologo_id?: number;
        excluir_cita_id?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HuecoResponse'][];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
}
