/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/usuarios/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Ver un usuario
     * @description Permiso: usuarios.ver.
     */
    get: operations['obtener'];
    /**
     * Editar usuario, correo y nombre
     * @description Permiso: usuarios.editar.
     */
    put: operations['editar'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/usuarios/{id}/roles': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Cambiar sus roles
     * @description Permiso: usuarios.asignar_roles. Sustituye todos sus roles.
     */
    put: operations['cambiarRoles'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/usuarios/{id}/password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Restablecer su contraseña
     * @description Permiso: usuarios.editar. Cierra todas sus sesiones. La propia contraseña se cambia en /api/auth/password.
     */
    put: operations['restablecerPassword'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/usuarios/{id}/estado': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Activar o desactivar
     * @description Permiso: usuarios.editar. Desactivar cierra sus sesiones al momento; activar quita también un bloqueo por intentos fallidos.
     */
    put: operations['cambiarEstado'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/roles/{id}/permisos': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Cambiar los permisos de un rol
     * @description Permiso: roles.editar. Sustituye todos sus permisos. Los del administrador no se pueden cambiar (409).
     */
    put: operations['cambiarPermisos'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Cambiar mi contraseña
     * @description Pide la contraseña actual. Cierra las sesiones abiertas en otros equipos.
     */
    put: operations['cambiarPassword'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/usuarios': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Buscar usuarios
     * @description Permiso: usuarios.ver. Ordenados por nombre.
     */
    get: operations['buscar'];
    put?: never;
    /**
     * Crear un usuario
     * @description Permiso: usuarios.crear. Darle roles exige además usuarios.asignar_roles; el rol de administrador solo lo da un administrador.
     */
    post: operations['crear'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/contacto': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['enviar'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/citas': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['reservar'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Renovar el token de acceso
     * @description Usa la cookie de sesión. 401 si la sesión caducó o se cerró.
     */
    post: operations['renovar'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Cerrar sesión
     * @description Cierra la sesión de la cookie y la borra.
     */
    post: operations['cerrar'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Iniciar sesión
     * @description Con usuario o correo y contraseña. Devuelve el token de acceso y deja el de refresco en una cookie HttpOnly. 401 si los datos no son correctos; 423 si la cuenta está bloqueada por intentos fallidos.
     */
    post: operations['login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/tratamientos': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['listar'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/tratamientos/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['obtener_1'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/roles': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Roles con sus permisos
     * @description Permiso: roles.ver o usuarios.asignar_roles (para elegir los roles de un usuario).
     */
    get: operations['listar_1'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/permisos': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Todos los permisos que existen
     * @description Permiso: roles.ver.
     */
    get: operations['permisos'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/odontologos': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['listar_2'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/odontologos/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['obtener_2'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['health'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/disponibilidad': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['dia'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/disponibilidad/proximos': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['proximos'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Usuario con sesión iniciada
     * @description Sus datos, roles y permisos.
     */
    get: operations['yo'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auditoria': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Consultar la auditoría
     * @description Permiso: auditoria.ver. De lo más reciente a lo más antiguo.
     */
    get: operations['buscar_1'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    UsuarioEdicionRequest: {
      username: string;
      /** Format: email */
      email: string;
      nombre: string;
    };
    RolResumen: {
      codigo: string;
      nombre: string;
    };
    /** @description Usuario del software de gestión. Las fechas están en hora de Madrid. */
    UsuarioResponse: {
      /** Format: int64 */
      id: number;
      username: string;
      email: string;
      nombre: string;
      activo: boolean;
      /** @description Bloqueado temporalmente por demasiados intentos fallidos */
      bloqueado: boolean;
      /** Format: date-time */
      bloqueado_hasta?: string;
      /** Format: date-time */
      ultimo_acceso?: string;
      /** Format: date-time */
      creado_en: string;
      roles: components['schemas']['RolResumen'][];
    };
    RolesUsuarioRequest: {
      roles: string[];
    };
    PasswordRequest: {
      password: string;
    };
    EstadoUsuarioRequest: {
      activo: boolean;
    };
    PermisosRolRequest: {
      permisos: string[];
    };
    /** @description Rol con sus permisos */
    RolResponse: {
      /** Format: int64 */
      id: number;
      codigo: string;
      nombre: string;
      descripcion?: string;
      /** @description false en el administrador: tiene siempre todos los permisos */
      editable: boolean;
      /**
       * Format: int64
       * @description Usuarios que tienen este rol
       */
      usuarios: number;
      /** @description Códigos de sus permisos */
      permisos: string[];
    };
    CambioPasswordRequest: {
      password_actual: string;
      password_nueva: string;
    };
    UsuarioCreacionRequest: {
      username: string;
      /** Format: email */
      email: string;
      nombre: string;
      password: string;
      roles?: string[];
    };
    ContactoRequest: {
      nombre: string;
      telefono: string;
      /** Format: email */
      email: string;
      tratamiento?: string;
      mensaje?: string;
    };
    ApiResponse: {
      success?: boolean;
      message?: string;
      errores?: {
        [key: string]: string;
      };
      datos?: Record<string, never>;
    };
    CitaRequest: {
      /** Format: int64 */
      tratamiento_id: number;
      /** Format: int64 */
      odontologo_id: number;
      /** Format: date */
      fecha: string;
      /** Format: time-local */
      hora_inicio: string;
      nombre: string;
      telefono: string;
      /** Format: email */
      email: string;
      mensaje?: string;
    };
    /** @description Sesión iniciada */
    SesionResponse: {
      /** @description Token de acceso (JWT) de corta duración */
      token_acceso: string;
      /** @example Bearer */
      tipo: string;
      /**
       * Format: int64
       * @description Segundos que dura el token de acceso
       * @example 900
       */
      expira_en: number;
      usuario: components['schemas']['UsuarioActualResponse'];
    };
    /** @description Usuario con sesión iniciada */
    UsuarioActualResponse: {
      /** Format: int64 */
      id: number;
      username: string;
      email: string;
      nombre: string;
      roles: components['schemas']['RolResumen'][];
      /**
       * @description Códigos de los permisos que suman sus roles
       * @example [
       *       "usuarios.ver",
       *       "auditoria.ver"
       *     ]
       */
      permisos: string[];
    };
    LoginRequest: {
      usuario: string;
      password: string;
    };
    /** @description Página de resultados */
    PaginaResponseUsuarioResponse: {
      contenido: components['schemas']['UsuarioResponse'][];
      /**
       * Format: int32
       * @description Número de página, empezando en 0
       */
      pagina: number;
      /**
       * Format: int32
       * @description Resultados por página
       */
      tamano: number;
      /** Format: int64 */
      total_elementos: number;
      /** Format: int32 */
      total_paginas: number;
    };
    TratamientoResponse: {
      /** Format: int64 */
      id?: number;
      nombre?: string;
      descripcion?: string;
      descripcion_corta?: string;
      precio_desde?: number;
      duracion_aproximada?: string;
      /** Format: int32 */
      duracion_minutos?: number;
      imagen?: string;
      odontologo_ids?: number[];
    };
    PermisoResponse: {
      /** Format: int64 */
      id: number;
      codigo: string;
      modulo: string;
      descripcion: string;
    };
    OdontologoResponse: {
      /** Format: int64 */
      id?: number;
      nombre?: string;
      especialidad?: string;
      descripcion?: string;
      imagen?: string;
    };
    DisponibilidadResponse: {
      /** Format: date */
      fecha?: string;
      tratamiento?: components['schemas']['TratamientoResumen'];
      horarios?: components['schemas']['HorarioDisponibleResponse'][];
      proximas_opciones?: components['schemas']['HorarioDisponibleResponse'][];
      mensaje?: string;
    };
    HorarioDisponibleResponse: {
      /** Format: date */
      fecha?: string;
      /** Format: time-local */
      hora_inicio?: string;
      /** Format: time-local */
      hora_fin?: string;
      /** Format: int64 */
      odontologo_id?: number;
      odontologo_nombre?: string;
      odontologo_especialidad?: string;
    };
    TratamientoResumen: {
      /** Format: int64 */
      id?: number;
      nombre?: string;
      /** Format: int32 */
      duracion_minutos?: number;
    };
    /** @description Operación registrada en la auditoría. La fecha está en hora de Madrid. */
    AuditoriaResponse: {
      /** Format: int64 */
      id: number;
      /** Format: date-time */
      creado_en: string;
      usuario?: components['schemas']['UsuarioResumen'];
      /** @enum {string} */
      origen: 'LANDING' | 'SOFTWARE' | 'APP' | 'SISTEMA';
      /** @enum {string} */
      accion:
        | 'INICIAR_SESION'
        | 'INICIO_SESION_FALLIDO'
        | 'BLOQUEAR_POR_INTENTOS'
        | 'CERRAR_SESION'
        | 'CAMBIAR_PASSWORD'
        | 'RESTABLECER_PASSWORD'
        | 'CREAR'
        | 'EDITAR'
        | 'ACTIVAR'
        | 'DESACTIVAR'
        | 'CAMBIAR_ROLES'
        | 'CAMBIAR_PERMISOS'
        | 'RESERVAR'
        | 'CANCELAR'
        | 'REPROGRAMAR';
      /** @enum {string} */
      entidad: 'USUARIO' | 'ROL' | 'CITA';
      entidad_id?: string;
      valor_anterior?: components['schemas']['JsonNode'];
      valor_nuevo?: components['schemas']['JsonNode'];
      ip?: string;
    };
    /** @description Datos en formato JSON */
    JsonNode: {
      [key: string]: unknown;
    };
    /** @description Página de resultados */
    PaginaResponseAuditoriaResponse: {
      contenido: components['schemas']['AuditoriaResponse'][];
      /**
       * Format: int32
       * @description Número de página, empezando en 0
       */
      pagina: number;
      /**
       * Format: int32
       * @description Resultados por página
       */
      tamano: number;
      /** Format: int64 */
      total_elementos: number;
      /** Format: int32 */
      total_paginas: number;
    };
    /** @description Quién lo hizo; vacío si fue un paciente desde la web o el propio sistema */
    UsuarioResumen: {
      /** Format: int64 */
      id: number;
      username: string;
      nombre: string;
    };
    /** @description Error de la API */
    ErrorResponse: {
      /**
       * Format: date-time
       * @description Momento del error
       * @example 2026-10-12T10:25:00+02:00
       */
      timestamp: string;
      /**
       * Format: int32
       * @description Código HTTP
       * @example 409
       */
      status: number;
      /**
       * @description Nombre del código HTTP
       * @example CONFLICT
       */
      error: string;
      /**
       * @description Mensaje para mostrar a la persona
       * @example Este horario acaba de ser reservado. Selecciona otra opción.
       */
      message: string;
      /**
       * @description Ruta de la petición
       * @example /api/citas
       */
      path: string;
      /**
       * @description Un mensaje por cada campo con datos no válidos
       * @example {
       *       "email": "Escribe un correo válido."
       *     }
       */
      errores?: {
        [key: string]: string;
      };
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  obtener: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UsuarioResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  editar: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UsuarioEdicionRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UsuarioResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  cambiarRoles: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RolesUsuarioRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UsuarioResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  restablecerPassword: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  cambiarEstado: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EstadoUsuarioRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UsuarioResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  cambiarPermisos: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PermisosRolRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RolResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  cambiarPassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CambioPasswordRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  buscar: {
    parameters: {
      query?: {
        /** @description Parte del nombre, del usuario o del correo */
        texto?: string;
        /** @description true = activos, false = desactivados, vacío = todos */
        activo?: boolean;
        pagina?: number;
        tamano?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginaResponseUsuarioResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  crear: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UsuarioCreacionRequest'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UsuarioResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  enviar: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ContactoRequest'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  reservar: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CitaRequest'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  renovar: {
    parameters: {
      query?: never;
      header: {
        /**
         * @description Siempre XMLHttpRequest. Protege la cookie de sesión frente a peticiones desde otras webs.
         * @example XMLHttpRequest
         */
        'X-Requested-With': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SesionResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  cerrar: {
    parameters: {
      query?: never;
      header: {
        /**
         * @description Siempre XMLHttpRequest. Protege la cookie de sesión frente a peticiones desde otras webs.
         * @example XMLHttpRequest
         */
        'X-Requested-With': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SesionResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  listar: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TratamientoResponse'][];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  obtener_1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TratamientoResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  listar_1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RolResponse'][];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  permisos: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PermisoResponse'][];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  listar_2: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OdontologoResponse'][];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  obtener_2: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OdontologoResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  dia: {
    parameters: {
      query: {
        tratamiento_id: number;
        fecha: string;
        odontologo_id?: number;
        franja?: 'MANANA' | 'TARDE';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DisponibilidadResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  proximos: {
    parameters: {
      query: {
        tratamiento_id: number;
        desde?: string;
        odontologo_id?: number;
        franja?: 'MANANA' | 'TARDE';
        limite?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DisponibilidadResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  yo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UsuarioActualResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  buscar_1: {
    parameters: {
      query?: {
        entidad?: 'USUARIO' | 'ROL' | 'CITA';
        /** @description Identificador del registro afectado */
        entidad_id?: string;
        /** @description Quién lo hizo */
        usuario_id?: number;
        accion?:
          | 'INICIAR_SESION'
          | 'INICIO_SESION_FALLIDO'
          | 'BLOQUEAR_POR_INTENTOS'
          | 'CERRAR_SESION'
          | 'CAMBIAR_PASSWORD'
          | 'RESTABLECER_PASSWORD'
          | 'CREAR'
          | 'EDITAR'
          | 'ACTIVAR'
          | 'DESACTIVAR'
          | 'CAMBIAR_ROLES'
          | 'CAMBIAR_PERMISOS'
          | 'RESERVAR'
          | 'CANCELAR'
          | 'REPROGRAMAR';
        /** @description Desde este día (incluido), hora de Madrid */
        desde?: string;
        /** @description Hasta este día (incluido), hora de Madrid */
        hasta?: string;
        pagina?: number;
        tamano?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginaResponseAuditoriaResponse'];
        };
      };
      /** @description Error (400 datos no válidos, 401 sin sesión, 403 sin permiso, 404 no existe, 409 conflicto, 429 demasiadas peticiones…) */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
}
